### ISSUE TITLE
Parse module from VkShaderModuleCreateInfo

### ISSUE THREAD

**Issue by Yamakaky** [google/rspirv#2]
`[VkShaderModuleCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkShaderModuleCreateInfo.html)` allow us to get a &[u32]. How can I parse it with `rspirv`? `load` only supports `Vec<u8>`.
For the record, I'm working on https://github.com/Yamakaky/cendre.

**Comment by Yamakaky** [comment]
I just did
```
let code = unsafe {
    slice::from_raw_parts(infos.pCode as *const u8,
                          infos.codeSize)
};
```
It seems to work.

**Comment by antiagainst** [comment]
Yep, that works. :)

It seems that another `load()` function taking `Vec<u32>` as parameter would be useful. I was doing all previous prototyping based on some shaders from disk, which is read in using `fs::File::read_to_end`. That signature requires `Vec<u8>`.

And another problem just occurred to me. `load()` should not require ownership of the passed in data. Actually taking `&[u8]` is better since it avoids copying the whole data. I'll do the change.

**Comment by Yamakaky** [comment]
The spec defines spur as a stream of u32, so yeah it makes sense.

**Comment by antiagainst** [comment]
This is done via https://github.com/google/rspirv/commit/742db903373849a8752821489208eedaf07d981a.

**Comment by Yamakaky** [comment]
Cool!

**Comment by antiagainst** [comment]
@Yamakaky: FYI, a new release [v0.3.0](https://crates.io/crates/rspirv/0.3.0) was published with the change incorporated. :)

**Comment by Yamakaky** [comment]
Just saw that ;)
