### ISSUE TITLE
function parameters not being assembled

### ISSUE THREAD

**Issue by tedsta** [google/rspirv#8]
https://github.com/google/rspirv/blob/master/rspirv/binary/assemble.rs#L118-L132

Found this after a few hours of debugging a crash when trying to run a generated spir-v binary in intel's experimental OpenCL 2.1 CPU driver. Wish they had a nice error message rather than just segfaulting!

**Comment by antiagainst** [comment]
Ouch! That's a terrible oversight. I gonna fix it soon. Deeply sorry for the time loss caused by it! I should really write more tests to tighten these things to squeeze bugs out. I'll do that this weekend.

For preventing this happening again, [SPIR-V validator](https://github.com/KhronosGroup/SPIRV-Tools#validator) may do some good. Although it's basically for targeting graphics on Vulkan right now, still worth a try when you see something goes wrong.

**Comment by tedsta** [comment]
No worries! Thanks for the tip, will try it out.
